import type { ToolId } from '../../shared/types';
export const catalog: Record<
  ToolId,
  { name: string; binary: string; args: string[]; brew?: string; winget?: string; url: string }
> = {
  git: {
    name: 'Git',
    binary: 'git',
    args: ['--version'],
    brew: 'git',
    winget: 'Git.Git',
    url: 'https://git-scm.com/downloads',
  },
  node: {
    name: 'Node.js',
    binary: 'node',
    args: ['--version'],
    brew: 'node',
    winget: 'OpenJS.NodeJS.LTS',
    url: 'https://nodejs.org/en/download',
  },
  npm: {
    name: 'npm',
    binary: 'npm',
    args: ['--version'],
    url: 'https://docs.npmjs.com/downloading-and-installing-node-js-and-npm',
  },
  pnpm: {
    name: 'pnpm',
    binary: 'pnpm',
    args: ['--version'],
    brew: 'pnpm',
    winget: 'pnpm.pnpm',
    url: 'https://pnpm.io/installation',
  },
  yarn: {
    name: 'Yarn',
    binary: 'yarn',
    args: ['--version'],
    brew: 'yarn',
    url: 'https://yarnpkg.com/getting-started/install',
  },
  bun: {
    name: 'Bun',
    binary: 'bun',
    args: ['--version'],
    winget: 'Oven-sh.Bun',
    url: 'https://bun.sh/docs/installation',
  },
  python: {
    name: 'Python',
    binary: 'python3',
    args: ['--version'],
    brew: 'python',
    winget: 'Python.Python.3.13',
    url: 'https://www.python.org/downloads/',
  },
  uv: {
    name: 'uv',
    binary: 'uv',
    args: ['--version'],
    brew: 'uv',
    winget: 'astral-sh.uv',
    url: 'https://docs.astral.sh/uv/getting-started/installation/',
  },
  poetry: {
    name: 'Poetry',
    binary: 'poetry',
    args: ['--version'],
    brew: 'poetry',
    winget: 'Python.Poetry',
    url: 'https://python-poetry.org/docs/#installation',
  },
  rust: {
    name: 'Rust',
    binary: 'rustc',
    args: ['--version'],
    brew: 'rust',
    winget: 'Rustlang.Rustup',
    url: 'https://www.rust-lang.org/tools/install',
  },
  cargo: {
    name: 'Cargo',
    binary: 'cargo',
    args: ['--version'],
    brew: 'rust',
    winget: 'Rustlang.Rustup',
    url: 'https://www.rust-lang.org/tools/install',
  },
  go: {
    name: 'Go',
    binary: 'go',
    args: ['version'],
    brew: 'go',
    winget: 'GoLang.Go',
    url: 'https://go.dev/dl/',
  },
  java: {
    name: 'Java',
    binary: 'java',
    args: ['-version'],
    brew: 'openjdk',
    winget: 'EclipseAdoptium.Temurin.21.JDK',
    url: 'https://adoptium.net/',
  },
  maven: {
    name: 'Maven',
    binary: 'mvn',
    args: ['--version'],
    brew: 'maven',
    winget: 'Apache.Maven',
    url: 'https://maven.apache.org/install.html',
  },
  gradle: {
    name: 'Gradle',
    binary: 'gradle',
    args: ['--version'],
    brew: 'gradle',
    winget: 'Gradle.Gradle',
    url: 'https://gradle.org/install/',
  },
  ruby: {
    name: 'Ruby',
    binary: 'ruby',
    args: ['--version'],
    brew: 'ruby',
    winget: 'RubyInstallerTeam.RubyWithDevKit.3.3',
    url: 'https://www.ruby-lang.org/en/downloads/',
  },
  bundler: { name: 'Bundler', binary: 'bundle', args: ['--version'], url: 'https://bundler.io/' },
  php: {
    name: 'PHP',
    binary: 'php',
    args: ['--version'],
    brew: 'php',
    winget: 'PHP.PHP.8.4',
    url: 'https://www.php.net/downloads.php',
  },
  composer: {
    name: 'Composer',
    binary: 'composer',
    args: ['--version'],
    brew: 'composer',
    winget: 'Composer.Composer',
    url: 'https://getcomposer.org/download/',
  },
  dotnet: {
    name: '.NET SDK',
    binary: 'dotnet',
    args: ['--version'],
    brew: 'dotnet',
    winget: 'Microsoft.DotNet.SDK.8',
    url: 'https://dotnet.microsoft.com/download',
  },
  docker: {
    name: 'Docker',
    binary: 'docker',
    args: ['--version'],
    brew: 'docker',
    winget: 'Docker.DockerDesktop',
    url: 'https://www.docker.com/products/docker-desktop/',
  },
};
