import type { Machine, Scan } from '../shared/types';
export const demoMachine: Machine = {
  platform: 'darwin',
  label: 'macOS',
  arch: 'arm64',
  release: 'Example device',
  checkedAt: '2026-10-05T12:00:00Z',
  tools: [
    { id: 'git', name: 'Git', version: '2.49.0', path: '/example/bin/git' },
    { id: 'node', name: 'Node.js', version: '22.14.0', path: '/example/bin/node' },
    { id: 'pnpm', name: 'pnpm', version: null, path: null },
    { id: 'python', name: 'Python', version: '3.13.2', path: '/example/bin/python3' },
    { id: 'docker', name: 'Docker', version: null, path: null },
  ],
};
export const demoScan: Scan = {
  id: 'demo',
  checkedAt: '2026-10-05T12:00:00Z',
  machine: demoMachine,
  repository: {
    provider: 'github',
    owner: 'acme',
    name: 'studio',
    url: 'https://github.com/acme/studio',
    cloneUrl: 'https://github.com/acme/studio.git',
    branch: 'main',
    commit: 'a1b2c3d4e5f67890123456789012345678901234',
    description: 'An example full-stack workspace for your next idea.',
    stars: 1240,
    language: 'TypeScript',
    license: 'MIT',
  },
  requirements: [
    {
      id: 'git',
      tool: 'git',
      name: 'Git',
      range: '>=2',
      source: 'Repository',
      reason: 'Downloads the repository to your computer.',
      installed: '2.49.0',
      status: 'ready',
    },
    {
      id: 'node',
      tool: 'node',
      name: 'Node.js',
      range: '>=20 <23',
      source: 'package.json',
      reason: 'Runs the JavaScript application.',
      installed: '22.14.0',
      status: 'ready',
    },
    {
      id: 'pnpm',
      tool: 'pnpm',
      name: 'pnpm',
      range: '9.15.0',
      source: 'package.json',
      reason: 'Installs the project’s packages.',
      installed: null,
      status: 'missing',
    },
    {
      id: 'python',
      tool: 'python',
      name: 'Python',
      range: '>=3.10 <3.13',
      source: 'api/pyproject.toml',
      reason: 'Runs the Python API.',
      installed: '3.13.2',
      status: 'mismatch',
    },
    {
      id: 'docker',
      tool: 'docker',
      name: 'Docker',
      range: '*',
      source: 'compose.yaml',
      reason: 'Runs the local database in a container.',
      installed: null,
      status: 'missing',
    },
  ],
  projects: [
    {
      id: 'package.json',
      directory: '.',
      name: 'studio-web',
      ecosystem: 'JavaScript',
      frameworks: ['Next.js', 'React', 'TypeScript'],
      dependencies: 24,
      manager: 'pnpm',
      scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
    },
    {
      id: 'api/pyproject.toml',
      directory: 'api',
      name: 'studio-api',
      ecosystem: 'Python',
      frameworks: ['FastAPI'],
      dependencies: 8,
      manager: 'python',
      scripts: {},
    },
  ],
  files: ['package.json', 'pnpm-lock.yaml', 'api/pyproject.toml', 'compose.yaml', '.env.example'],
  notices: [
    'This is a sample report with example data. No repository or system check has been performed.',
    'Set DATABASE_URL and AUTH_SECRET in your local .env file before starting this example project.',
    'Manifest checks cannot verify credentials, external services, or undocumented setup steps.',
  ],
};
